language: ruby
jdk: openjdk7
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
bundler_args: --without documentation
